version: '3.9'
services:
  web_server:
    image: anssi/fcsc2019-web-ceci-n-est-pas-une-pipe:latest
    ports:
      - "80:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: N9mpnvEyTtaGxfsznEBh
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d